[feature] piv: manage modification_limitation
CanalTP/kirin pull request #344
Opened 2020-11-06 15:52 UTC by patochectp

ref: ND-1114

2020-11-06 16:14 UTC, pbougue approved these changes
:smile: :+1: 

Is it possible to add a test?

2020-11-06 17:48 UTC, pbougue requested changes
Side-note: after #345 we'll have shorter train 23187 to copy/paste !

2020-11-06 17:48 UTC, pbougue commented on kirin/piv/model_maker.py
> +MANAGED_EVENTS = ["RETARD", "SUPPRESSION", "MODIFICATION_DESSERTE_SUPPRIMEE", "MODIFICATION_DESSERTE_SUPPRIMEE"]
```suggestion
MANAGED_EVENTS = ["RETARD", "SUPPRESSION", "MODIFICATION_DESSERTE_SUPPRIMEE", "MODIFICATION_LIMITATION"]
```

2020-11-06 17:48 UTC, pbougue commented on tests/fixtures/piv/stomp_20201022_23186_modification_limitation.json
> +                  "type":"MODIFICATION_DESSERTE_SUPPRIMEE",
```suggestion
                  "type":"MODIFICATION_LIMITATION",
```

2020-11-06 17:48 UTC, pbougue commented on tests/integration/piv_test.py
> +            # the second stop have been departure marked as deleted
minor
```suggestion
            # the second stop's departure have been marked as deleted
```

2020-11-06 18:34 UTC, woshilapin reviewed
Do we need a new fixture for this case or can it be merged into one of the existing fixture?

2020-11-06 19:07 UTC, pbougue commented on kirin/piv/model_maker.py
> +MANAGED_STOP_EVENTS = [
It had modification in a previous blacked version of the code... And it looks like black doesn't have one OK way for a given code :shrug:

2020-11-09 10:00 UTC, pbougue approved these changes

2020-11-09 14:09 UTC, woshilapin approved these changes

2020-11-09 14:13 UTC, merged