[tech] piv worker: manage concurrency
CanalTP/kirin pull request #357
Opened 2020-12-08 16:42 UTC by patochectp

ref: ND-1141

2020-12-08 18:57 UTC, pbougue commented on kirin/command/piv_worker.py
> +                if locked:
Whether Kirin gets the lock or not, `ack()` is called for the message, so the message is lost in case Kirin didn't get the lock (not treated but acknowledged), no?

I don't see any other outcome to that case, but it would be so nice to be able to test that (but maybe expensive).
Maybe first set the lock to mock a concurrent worker, then call piv_worker on a rabbit : reusing what's done into piv_worker_test.py + mock_debug + count message in queue if it's easy with kombu... or just see if the message gets consumed when removing the lock.

And then to fix that, probably more something like:
```python
try:
    lock_name = make_kirin_lock_name("piv_poller", self.builder.contributor.id)
    with get_lock(logger, lock_name, app.config[str("REDIS_LOCK_TIMEOUT_POLLER")]) as locked:
        if locked:
            try:
                wrap_build(self.builder, body)
            finally:
                #blabla
                message.ack()
except Exception as e:
    log_exception(e, "piv_worker")
```

2020-12-08 18:57 UTC, pbougue commented on tests/integration/piv_worker_test.py
> +            mock_debug.assert_has_calls(calls, any_order=False)
:heart: sweet.
It may allow tests that would be super-expensive to do otherwise! It's sometimes a bit hacky but way better than nothing and quite cheap :+1:

2020-12-08 18:57 UTC, pbougue commented on kirin/command/piv_worker.py
> +                    wrap_build(self.builder, body)
I wonder if we should wait a bit (like 1s) before retrying when we don't get the lock.
To avoid stressing redis and rabbit too much doing nothing.
It would probably end with always the same worker doing the job but it's fine I think (the other is a backup).

So adding (not tested, didn't check time unit):
```python
                else:  # if not locked
                    sleep(1)
```

2020-12-09 08:05 UTC, woshilapin submitted a review, later dismissed

2020-12-09 08:05 UTC, woshilapin commented on tests/integration/piv_worker_test.py
> +            mock_debug.assert_has_calls(calls, any_order=False)
I agree, sweet test :heart_eyes:

2020-12-09 08:27 UTC, patochectp commented on kirin/utils.py
> +    logger.debug("getting lock %s" % lock_name)
with comma version I'm getting `getting lock %s', u'kirin.lock|piv_poller|rt.piv` instead of `getting lock kirin.lock|piv_poller|rt.piv`

2020-12-09 08:48 UTC, woshilapin commented on kirin/utils.py
> +    logger.debug("getting lock %s" % lock_name)
Weird. Since we mostly use the following syntax usually, any reason to use the `%` operator here. This is truly a naive question since I do not really know the consequence of using one or the other.

```suggestion
    logger.debug("getting lock {}".format(lock_name)) 
```

2020-12-09 11:32 UTC, patochectp commented on kirin/utils.py
> +    logger.debug("getting lock %s" % lock_name)
You're right, with a comma the message is properly formatted in the console but not with the mock. I’ll find another solution

2020-12-09 12:51 UTC, woshilapin commented on kirin/utils.py
> +    logger.debug("getting lock %s" % lock_name)
Ah, that is the `mock`. So I think it's actually fine keeping how it was before and changing how the tests to something like `call("getting lock %s", "kirin.lock|piv_poller|rt.piv")`. If I understand correctly, the `mock` is only testing how the mock was called (with which arguments so it expects the same one).

2020-12-09 13:00 UTC, patochectp commented on kirin/utils.py
> +    logger.debug("getting lock %s" % lock_name)
That's what I did

2020-12-14 10:18 UTC, woshilapin commented on kirin/command/piv_worker.py
> +        if datetime.now() - self.last_lock_update > CONF_LOCK_EXPIRE - timedelta(seconds=2):
Why do you have a ` - timedelta(seconds=2)` here? It looks like you're will refresh the lock expiration value and want to catch it before it's outdated... but I'm not sure. Maybe a comment would help if that's the case. (and 1 second is not enough ? how about using 5 seconds or more to be sure ?).

2020-12-14 10:18 UTC, woshilapin commented on kirin/command/piv_worker.py
> +            redis_client.expire(self.lock_name, CONF_LOCK_EXPIRE)
Just me complaining about something we cannot do anything about...

This `.expire()` has really a misleading name. I would expect calling this method expires a lock right now... but it is actually to set the delay for expiration if I understand correctly! Weird API in my opinion but not your fault.

2020-12-14 10:18 UTC, woshilapin commented on kirin/command/piv_worker.py
> +    lock_name = "{}|{}".format(app.config[str("TASK_LOCK_PREFIX")], PIV_POLLER)
Is this to enforce we're going to have only one `PivWorker` running at a time? If yes, I suggest the comment above to also make this precision. Something like

```
     # We assume one and only one PIV contributor is going to exist in the DB.
     # Therefore, we enforce one and only one `PivWorker` is running at a time.
```

2020-12-14 10:18 UTC, woshilapin commented on kirin/command/piv_worker.py
> +    def __init__(self, contributor, lock_name):
I see how we might use this new parameter in the future but for now, there is only one `PivWorker`, only one `lock_name`, so the name of the lock could just be a global constant, and we wouldn't need this new parameter.

2020-12-14 10:18 UTC, woshilapin commented on kirin/command/piv_worker.py
> +                redis_client.delete(lock_name)
Should we also remove the lock inside the `PivWorker` itself when we quit it (line [15](https://github.com/CanalTP/kirin/pull/357/files#diff-ac2785653924e36dfb16946d557b7c72e51fea24bac926570c14e24589d796f4R159))? That said, I'm worried that we release the lock maybe too early if do this...

2020-12-14 15:36 UTC, patochectp commented on kirin/command/piv_worker.py
> +            if locked:
if we have 2 piv_worker we can try to delete a lock of the other worker and will fail

2020-12-14 15:51 UTC, patochectp commented on kirin/command/piv_worker.py
> +                if locked:
Code above don't write in db, just read and I think that the lock must be as close as possible to the modifications

2020-12-15 10:06 UTC, patochectp commented on kirin/command/piv_worker.py
> +    lock_name = "{}|{}".format(app.config[str("TASK_LOCK_PREFIX")], PIV_POLLER)
done in 498b92964bcdcbbf488b3abec5acd2ac7431b7f9

2020-12-15 10:06 UTC, patochectp commented on kirin/command/piv_worker.py
> +    def __init__(self, contributor, lock_name):
done in 498b92964bcdcbbf488b3abec5acd2ac7431b7f9

2020-12-15 10:06 UTC, patochectp commented on kirin/command/piv_worker.py
> +                redis_client.delete(lock_name)
done in 498b92964bcdcbbf488b3abec5acd2ac7431b7f9

2020-12-15 10:07 UTC, patochectp commented on kirin/command/piv_worker.py
> +            redis_client.expire(self.lock_name, CONF_LOCK_EXPIRE)
done in 498b92964bcdcbbf488b3abec5acd2ac7431b7f9

2020-12-15 10:07 UTC, patochectp commented on kirin/command/piv_worker.py
> +PIV_POLLER = "piv_poller"
done in 498b92964bcdcbbf488b3abec5acd2ac7431b7f9

2020-12-15 10:07 UTC, patochectp commented on kirin/command/piv_worker.py
> +                if locked:
done in 498b92964bcdcbbf488b3abec5acd2ac7431b7f9

2020-12-15 10:07 UTC, patochectp commented on kirin/command/piv_worker.py
> +            if locked:
done in 498b92964bcdcbbf488b3abec5acd2ac7431b7f9

2020-12-15 10:13 UTC, woshilapin commented on kirin/command/piv_worker.py
> +            redis_client.expire(self.lock_name, CONF_LOCK_EXPIRE)
I'm not sure I agree with this because `on_iteration()` is not called every CPU clock cycle but more something like every second. So if `PIV_WORKER_REDIS_TIMEOUT_LOCK` is less than 5 seconds, there is a high chance you actually miss it. Maybe a minimum value of 1 second would help?

2020-12-15 10:18 UTC, patochectp commented on kirin/command/piv_worker.py
> +            redis_client.expire(self.lock_name, CONF_LOCK_EXPIRE)
Default REDIS_LOCK_TIMEOUT_POLLER is 5 min

2020-12-15 10:19 UTC, woshilapin commented on kirin/command/piv_worker.py
> +                redis_client.delete(lock_name)
I do not see what has been done for that comment. Note that I mistakenly wrote `line 15` instead of `line 159` (I fixed it since, but the link was correct). Maybe this has mislead you...

2020-12-15 10:21 UTC, woshilapin commented on kirin/command/piv_worker.py
> +            redis_client.expire(self.lock_name, CONF_LOCK_EXPIRE)
Sure, but it is configurable and it's actually very likely you'll put a very low value if you try to write tests on it.

2020-12-15 10:26 UTC, patochectp commented on kirin/command/piv_worker.py
> +                redis_client.delete(lock_name)
redis_client.delete has been removed at the request of @pbougue because the lock is removed when we released it

2020-12-15 10:31 UTC, woshilapin commented on kirin/command/piv_worker.py
> +                redis_client.delete(lock_name)
Ah OK, didn't understand that part. I'm resolving this conversation then.

2020-12-15 13:02 UTC, woshilapin commented on kirin/command/piv_worker.py
> +            redis_client.expire(self.lock_name, CONF_LOCK_EXPIRE)
As discussed together, maybe a fifth is a good idea, as long as it is bigger than at least 2 seconds. So something like this maybe?

```python
max(PIV_WORKER_REDIS_TIMEOUT_LOCK // 5, timedelta(seconds=2))
```

@pbougue What do you think?

2020-12-15 13:44 UTC, pbougue commented on tests/integration/piv_worker_test.py
> +            mock_debug.assert_any_call("lock {%s} updated", PIV_LOCK_NAME)
* Here you only test lock refresh, and it seems a bit lucky that the processing is longer than the interval between refresh, no?
* Can you test lock is acquired through `mock_debug.assert_any_call("getting lock %s", PIV_LOCK_NAME)`?
* It's nice to test that processing is still done, but it's not needed to acquire the lock (so it may be replaced by the sleep only if it's already tested elsewhere)
* No check that it's released (should only be the case if conf changes I guess and doable via `mock_debug.assert_any_call("releasing lock %s", PIV_LOCK_NAME)`).

```suggestion
            # Check lock acquired and refreshed
            mock_debug.assert_any_call("getting lock %s", PIV_LOCK_NAME)
            sleep((PIV_WORKER_REDIS_TIMEOUT_LOCK // 5) + 1)
            mock_debug.assert_any_call("lock {%s} updated", PIV_LOCK_NAME)
```

2020-12-15 13:44 UTC, pbougue commented on kirin/command/piv_worker.py
> +            redis_client.expire(self.lock_name, CONF_LOCK_EXPIRE)
Not sure about the subject here (looking at [**the current code**](https://github.com/CanalTP/kirin/pull/357/files#diff-ac2785653924e36dfb16946d557b7c72e51fea24bac926570c14e24589d796f4R131-R132)):
1. If it's about the value of `PIV_WORKER_REDIS_TIMEOUT_LOCK` OK to have a minimum on it, but for now it's based on `REDIS_LOCK_TIMEOUT_POLLER` directly (the one from GTFSRT-pollers), so we should be safe.
I'm OK to have a dedicated parameter, separated from the one on GTFSRT-pollers, too.
2. If it's about the interval when refresh happens I don't think it's a good idea, as we would have a lock not refresh before it expires.

2020-12-15 13:45 UTC, pbougue reviewed
:+1: The cinematic is good to me, I don't think of tricky breaking case.

2020-12-15 13:57 UTC, patochectp commented on tests/integration/piv_worker_test.py
> +            mock_debug.assert_any_call("lock {%s} updated", PIV_LOCK_NAME)
We can't test getting and releasing lock because we only test the worker and not the wrapper

2020-12-15 13:59 UTC, pbougue commented on tests/integration/piv_worker_test.py
> +            mock_debug.assert_any_call("lock {%s} updated", PIV_LOCK_NAME)
Ah, true!
Then only the comment needs a "refresh" :stuck_out_tongue_closed_eyes:

2020-12-15 14:46 UTC, pbougue commented on kirin/command/piv_worker.py
> +        with get_lock(logger, PIV_LOCK_NAME, app.config[str("REDIS_LOCK_TIMEOUT_POLLER")]) as locked:
reminder: reuse the const TIMEOUT

2020-12-15 14:52 UTC, pbougue commented on kirin/command/piv_worker.py
> +PIV_WORKER_REDIS_TIMEOUT_LOCK = timedelta(seconds=float(str(app.config.get(str("REDIS_LOCK_TIMEOUT_POLLER")))))
As discussed :
```suggestion
PIV_WORKER_REDIS_TIMEOUT_LOCK = timedelta(seconds=max(float(str(app.config.get(str("REDIS_LOCK_TIMEOUT_POLLER"))))), 10)
```

2020-12-16 09:02 UTC, woshilapin approved these changes

2020-12-16 09:02 UTC, woshilapin commented on tests/integration/piv_worker_test.py
> +            # mock_debug.assert_called_once_with("lock {%s} updated", PIV_LOCK_NAME)
Maybe this can be removed.

2020-12-16 13:13 UTC, patochectp commented on tests/integration/piv_worker_test.py
> +            # mock_debug.assert_called_once_with("lock {%s} updated", PIV_LOCK_NAME)
done

2020-12-16 16:00 UTC, pbougue approved these changes

2020-12-16 16:00 UTC, pbougue commented on kirin/command/piv_worker.py
> +# shall not occur during this time otherwise the piv worker definitely died
minor:
```suggestion
# In case of postgresql disconnection, it seems that the timeout (so exception) takes 10 seconds to happen,
# the lock expiration shall not occur during this time otherwise it can lead to incorrect state (still working but unlocked)
```

2020-12-16 16:10 UTC, pbougue requested changes

2020-12-16 16:10 UTC, pbougue commented on kirin/command/piv_worker.py
> +            redis_client.expire(PIV_LOCK_NAME, PIV_WORKER_REDIS_TIMEOUT_LOCK)
```suggestion
            redis_client.expire(PIV_LOCK_NAME, PIV_WORKER_REDIS_TIMEOUT_LOCK.total_seconds())
```

2020-12-16 16:22 UTC, patochectp commented on kirin/command/piv_worker.py
> +            redis_client.expire(PIV_LOCK_NAME, PIV_WORKER_REDIS_TIMEOUT_LOCK)
``time`` can be represented by an integer or a Python timedelta object and tilmedelta has microsecond resolution thus total_seconds is a float

2020-12-16 16:32 UTC, pbougue commented on kirin/command/piv_worker.py
> +            redis_client.expire(PIV_LOCK_NAME, PIV_WORKER_REDIS_TIMEOUT_LOCK)
Ah yep, I didn't check https://github.com/andymccurdy/redis-py/blob/1a41cfd95a53a95b078084d8627be6b6fba3bb71/redis/client.py#L1651
:hand_over_mouth: sorry!

2020-12-16 16:33 UTC, pbougue approved these changes

2020-12-16 16:46 UTC, merged