[fix] not take into account deleted stop in check_stop_time_consistency
CanalTP/kirin pull request #366
Opened 2021-02-03 12:28 UTC by patochectp

ref: ND-1213

2021-02-03 12:57 UTC, woshilapin approved these changes
Code looks fine and from what I understand, business logic is fine but probably someone else with more context is needed for the review (:eyes: @pbougue :smile:)

2021-02-03 17:09 UTC, pbougue requested changes
I think we should change code, but I'm not sure that it's worth adding tests for those "extreme" cases (needs a bit of thinking to find a case that breaks with your current implem and not with a more precise implem).

2021-02-03 17:09 UTC, pbougue commented on tests/integration/piv_test.py
> +    """
Can you add a bit of explanation here?
Maybe hours, order of stops deleted, added (and 85010157) and a sentence like:
`Datetimes of stops are not correctly sorted when comparing to "rang", but it is correct anyway, as only deleted stops are incorrectly sorted.`

2021-02-08 18:50 UTC, pbougue approved these changes

2021-02-09 08:50 UTC, patochectp commented on kirin/piv/model_maker.py
>              _check_stop_time_consistency(
done in 5b964ccf72098af795b13082ff0077e59bdb0f5d

2021-02-09 08:51 UTC, patochectp commented on tests/integration/piv_test.py
> +    api_post("/piv/{}".format(PIV_CONTRIBUTOR_ID), data=ujson.dumps(piv_feed))
done in 5b964ccf72098af795b13082ff0077e59bdb0f5d

2021-02-09 10:34 UTC, pbougue approved these changes

2021-02-09 11:02 UTC, merged