last_valid_update change
CanalTP/kirin pull request #394
Opened 2021-09-07 08:42 UTC by Moomoo-Seukla

set min_date value for the status dates (last_valid_update, last_update) if no row fot a contributor.
pending 'status' when create a row in rtu

see : [ND-1527](https://jira.kisio.org/browse/ND-1527)

2021-09-07 14:58 UTC, pbougue requested changes
:warning: fn `poke_updated_at` must also be changed, as it may introduce date-flickering too: https://github.com/CanalTP/kirin/blob/8686ed58138db938877f69da1a7f38dd76dc34a0/kirin/utils.py#L250-L259

I would go for:
```python
def poke_updated_at(rtu):
    """
    just update the updated_at of the RealTimeUpdate object provided
    """
    if rtu:
        rtu.updated_at = datetime.datetime.utcnow
```

2021-09-07 14:58 UTC, pbougue commented on kirin/core/model.py
> +            sql = sql.filter(cls.status != "pending")
To avoid filter repetition below when reusing `sql` I would not add it for perf (don't know if SQL or sqlalchemy is smart enough to ignore useless filter).
So let build the `sql` query, then from that execute a different `sql_no_pending` query (but as it's probably a reference, you may need some kind of deepcopy to avoir side-effect).

2021-09-07 14:58 UTC, pbougue commented on tests/integration/test_end_point.py
> +    assert PIV_CONTRIBUTOR_DB_ID in resp["last_update"]
This is already checked below (tests will break when accessing `None ["toto"]`).

2021-09-07 14:58 UTC, pbougue commented on tests/integration/cots_test.py
> +    date_min_expected = (datetime.min.time()).strftime("%Y-%m-%dT%H:%M:%SZ")
Not worth a variable for one use only I guess.
(and please reuse utils if you put min_printable_datetime there)

2021-09-08 15:29 UTC, Moomoo-Seukla commented on kirin/core/build_wrapper.py
>          record_call(status, **log_dict)
This treatment is done in function `wrap_build` in `finally` execution. If status is KO or raise an exception, it's catch by `except`

2021-09-08 15:30 UTC, pbougue commented on kirin/core/build_wrapper.py
>          record_call(status, **log_dict)
You're only dealing with the OK case there, no?

2021-09-08 15:33 UTC, Moomoo-Seukla commented on kirin/core/build_wrapper.py
>          record_call(status, **log_dict)
yes

2021-09-08 15:37 UTC, pbougue commented on kirin/core/build_wrapper.py
>          record_call(status, **log_dict)
Then my proposition (which implies removing the "OK-case code" you add in this PR) is to separate this from logs and deal it once and for all cases.

2021-09-09 08:27 UTC, pbougue commented on kirin/core/build_wrapper.py
>          record_call(status, **log_dict)
As discussed, current code in your PR does work.
So my proposal would only make code clearer and a bit less error-prone.

2021-09-13 15:16 UTC, pbougue commented on kirin/cots/model_maker.py
> +            status="pending",
Please don't forget the second point of this remark :wink:

2021-09-13 16:28 UTC, pbougue requested changes
Please also change the `poke_updated_at`

2021-09-14 12:19 UTC, Moomoo-Seukla commented on kirin/cots/model_maker.py
> +            status="pending",
done.

2021-09-14 12:49 UTC, pbougue approved these changes

2021-09-15 12:40 UTC, merged