fix: add 'SET NULL' constraint to migration
CanalTP/kirin pull request #431
Opened 2021-12-03 13:36 UTC by woshilapin

Should address comment https://github.com/CanalTP/kirin/pull/428#discussion_r761918635. I've applied the `NOT NULL` constraint on `dev` DB manually too (so this migration should not be played again on next deployment).

2021-12-03 13:40 UTC, pbougue requested changes
This should only be part of #426, it's fully related and only related to #426 PR (and #426 PR won't work without it).

2021-12-03 14:16 UTC, pbougue approved these changes
Ahhh, the mixup was partly in my head on this, it's better with this indeed.

2021-12-06 16:05 UTC, pbougue commented on migrations/versions/1639faa28bc4_add_siri_et_lite_idfm.py
> +    op.execute("ALTER TABLE realtime_update ALTER COLUMN old_connector SET NOT NULL")
```suggestion
    op.execute("ALTER TABLE real_time_update ALTER COLUMN old_connector SET NOT NULL")
```

2021-12-06 16:05 UTC, pbougue commented on migrations/versions/1639faa28bc4_add_siri_et_lite_idfm.py
> +    op.execute("ALTER TABLE realtime_update ALTER COLUMN old_connector_type SET NOT NULL")
```suggestion
    op.execute("ALTER TABLE real_time_update ALTER COLUMN old_connector_type SET NOT NULL")
```

2021-12-06 16:09 UTC, woshilapin commented on migrations/versions/1639faa28bc4_add_siri_et_lite_idfm.py
> +    op.execute("ALTER TABLE realtime_update ALTER COLUMN old_connector SET NOT NULL")
:facepalm:

2021-12-06 16:09 UTC, woshilapin commented on migrations/versions/1639faa28bc4_add_siri_et_lite_idfm.py
> +    op.execute("ALTER TABLE realtime_update ALTER COLUMN old_connector_type SET NOT NULL")
:facepalm:

2021-12-06 16:25 UTC, merged