split kirin_status
CanalTP/kirin pull request #432
Opened 2021-12-08 09:33 UTC by Moomoo-Seukla

change 'record_call' function
split message 'kirin_status' into two messages 'kirin_feed_process_info' and 'kirin_reload_info'

tickets : [ND-1737](https://jira.kisio.org/browse/ND-1737) [ND-1704](https://jira.kisio.org/browse/ND-1704)

2021-12-08 10:12 UTC, woshilapin commented on kirin/rabbitmq_handler.py
> +            trip_pdates = TripUpdate.find_by_contributor_period(
```suggestion
            trip_updates = TripUpdate.find_by_contributor_period(
```

2021-12-08 10:12 UTC, woshilapin commented on kirin/core/build_wrapper.py
> +        "output_feed_size": sys.getsizeof(feed_str),
Something bothers me here. We add all these values in `log_dict` but we don't use them here (just returning `log_dict` from the function). Therefore, we do not know how `log_dict` is gonna be used (and especially if it's gonna be sent with event `kirin_feed_process_info`)... but that might be out of scope for your PR since you didn't change the code architecture :thinking:

2021-12-08 10:25 UTC, Moomoo-Seukla commented on kirin/rabbitmq_handler.py
> +            trip_pdates = TripUpdate.find_by_contributor_period(
Done bcad0a7

2021-12-08 10:33 UTC, Moomoo-Seukla commented on kirin/rabbitmq_handler.py
> +            record_call("kirin_reload_info", status, **log_dict)
No, it's `kirin_reload_info`. see https://jira.kisio.org/browse/ND-1737

2021-12-09 07:01 UTC, Moomoo-Seukla commented on kirin/core/build_wrapper.py
> +        "output_feed_size": sys.getsizeof(feed_str),
Exactly, it's same of 'builder.build_rt_update' (L160) and builder.build_trip_updates (L164) functions, log_dict is updated by functions return

2021-12-09 13:24 UTC, woshilapin commented on tests/integration/test_end_point.py
> +        resp_rt = rt_loader._on_request(message)
This looks like two different tests (happy-path, and failure mode). Wouldn't it be better to split into 2 functions (or a generic function with parameterized tests?).

2021-12-09 13:43 UTC, Moomoo-Seukla commented on tests/integration/test_end_point.py
> +        resp_rt = rt_loader._on_request(message)
done bddde0e

2021-12-09 13:46 UTC, woshilapin approved these changes

2021-12-09 19:27 UTC, pbougue requested changes
If you can hand-test locally the values on a real case after your corrections it would be nice :pray:

2021-12-09 19:27 UTC, pbougue commented on kirin/rabbitmq_handler.py
> +                    "input_feed_size": sys.getsizeof(body),
This is not relevant here, the size of the request for reload is not something we want to track.

2021-12-09 19:27 UTC, pbougue commented on kirin/rabbitmq_handler.py
> +                    "input_trip_update_count": len(trip_updates),
This is not relevant here.
`trip_updates` are just what's extracted from db and directly serialized to `feed.entity` so the number is always gonna be the same.
There is no "input" trip update on a reload as we did not process anything.

2021-12-09 19:27 UTC, pbougue commented on kirin/rabbitmq_handler.py
> +            record_custom_parameter("reason", e)
please also update the `log_dict`

2021-12-09 19:27 UTC, pbougue commented on kirin/rabbitmq_handler.py
> +        return log_dict
Not super fan of having something added to real code just for tests.
This may be OK though.

2021-12-09 19:27 UTC, pbougue commented on kirin/rabbitmq_handler.py
> +                record_custom_parameter("reason", e)
Please remove it, as discussed it's useless, caught in the larger try.

2021-12-09 19:27 UTC, pbougue commented on kirin/core/build_wrapper.py
> +        "input_trip_update_count": len(trip_updates),
This is gonna be more complicated than that, as this value is the same as `len(feed.entity)`.
We want to display the actual number of trips "described" in the raw_data... So this is gonna be dependent on the type of connector : something like increment a value each time we try to create one trip_update (no matter if it's a success or not).

2021-12-09 19:27 UTC, pbougue commented on tests/integration/test_end_point.py
> +    task = task_pb2.Task()
This is filled but never used, you should remove it.

2021-12-09 19:27 UTC, pbougue commented on tests/integration/test_end_point.py
> +        assert len(resp_rt) == 1
Can't you test the values in the log_dict?

2021-12-09 19:27 UTC, pbougue commented on tests/integration/test_end_point.py
> +        assert resp_rt["output_feed_size"] == 46
Can't you test the rest of the values in the log_dict?

2021-12-10 17:37 UTC, Moomoo-Seukla commented
> If you can hand-test locally the values on a real case after your corrections it would be nice pray

I tested it with real case

2021-12-13 17:38 UTC, Moomoo-Seukla commented on kirin/core/build_wrapper.py
> +        "input_trip_update_count": len(trip_updates),
done 6ce474a

2021-12-13 18:09 UTC, Moomoo-Seukla commented on tests/integration/test_end_point.py
> +        assert "encoding without a string argument" == resp_rt["reason"]
We have `duration` in case of invalid protobuf.

2021-12-13 18:14 UTC, pbougue commented on kirin/piv/model_maker.py
> +            log_dict.update({"input_trip_update_count": 0})
This is useless here, as `log_dict` is never gonna be reused in that case.

2021-12-13 18:14 UTC, pbougue commented on kirin/pollers/gtfs_rt/gtfs_rt_model_maker.py
> +        log_dict.update({"input_trip_update_count": len(trip_updates)})
There are some filters already applied in `_build_one_trip_update`, so this won't cover all inputs.

2021-12-13 18:14 UTC, pbougue commented on tests/integration/test_end_point.py
> +        assert "encoding without a string argument" == format(str(resp_rt["reason"]))
Why do you need `format`? `str` is not enough?

2021-12-13 18:14 UTC, pbougue commented on tests/integration/test_end_point.py
> +        assert "'str' object has no attribute 'clone'" == format(str(resp_rt["reason"]))
This is worth digging, I think.
I don't understand where it comes from.

2021-12-13 18:15 UTC, pbougue reviewed
I'm not sure how to handle this, but with the exceptions raised, we will get a lot of cases without an `input_trip_update_count` value...
We should put this count in a non-fallible part, which may not be free-of-charge for performance.

EDIT: to be handled later.

2021-12-13 18:16 UTC, pbougue commented on tests/integration/test_end_point.py
> +        assert "encoding without a string argument" == resp_rt["reason"]
We may just check it's there and > 0, I guess.

2021-12-13 18:39 UTC, Moomoo-Seukla commented on tests/integration/test_end_point.py
> +        assert "encoding without a string argument" == format(str(resp_rt["reason"]))
done 98c19b9

2021-12-13 18:39 UTC, Moomoo-Seukla commented on kirin/piv/model_maker.py
> +        log_dict.update({"input_trip_update_count": len(dict_objects[0])})
done 98c19b9

2021-12-13 18:39 UTC, Moomoo-Seukla commented on tests/integration/test_end_point.py
> +        assert "encoding without a string argument" == resp_rt["reason"]
done 98c19b9

2021-12-13 18:54 UTC, Moomoo-Seukla commented on tests/integration/test_end_point.py
> +        assert "encoding without a string argument" == format(str(resp_rt["reason"]))
remove format

2021-12-14 10:13 UTC, pbougue commented on kirin/pollers/gtfs_rt/gtfs_rt_model_maker.py
> +        log_dict.update({"input_trip_update_count": len(trip_updates)})
This is too complex to be done right away, all `input_trip_update_count` will be removed from this PR and handled later.

2021-12-14 10:14 UTC, pbougue commented on tests/integration/test_end_point.py
> +        assert "encoding without a string argument" == format(str(resp_rt["reason"]))
In all cases where "reason" is filled, let's use `str(e)`.
So here the `str` won't be necessary anymore.

2021-12-14 13:33 UTC, pbougue commented on kirin/piv/model_maker.py
> +        log_dict.update({"input_trip_update_count": len(dict_objects)})
You left this one.
This file should not move in this PR, in the end.

2021-12-14 13:33 UTC, pbougue commented on kirin/pollers/gtfs_rt/gtfs_rt_model_maker.py
> -
This file should not change at all in this PR.

2021-12-14 13:51 UTC, Moomoo-Seukla commented on kirin/pollers/gtfs_rt/gtfs_rt_model_maker.py
> +        log_dict.update({"input_trip_update_count": len(trip_updates)})
Done

2021-12-14 14:00 UTC, Moomoo-Seukla commented on kirin/piv/model_maker.py
> +        log_dict.update({"input_trip_update_count": len(dict_objects)})
Sorry, i remove it.

2021-12-14 16:17 UTC, pbougue commented on kirin/piv/model_maker.py
> +        log_dict.update({"input_trip_update_count": len(dict_objects)})
Then this file should not move, in the end.

2021-12-14 16:18 UTC, pbougue approved these changes
The file changed for nothing is just a minor remark, do it if you want, it's fine by me.

2021-12-14 16:18 UTC, Moomoo-Seukla commented on kirin/piv/model_maker.py
> +        log_dict.update({"input_trip_update_count": len(dict_objects)})
yes

2021-12-14 19:27 UTC, Moomoo-Seukla commented on kirin/rabbitmq_handler.py
> +                trip_updates,
done

2021-12-14 19:28 UTC, merged